// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AuthConfigInitParameters struct {

	// Authentication Information
	AuthInfo *string `json:"authInfo,omitempty" tf:"auth_info,omitempty"`

	// Authentication type. anonymous, function, or jwt.
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`
}

type AuthConfigObservation struct {

	// Authentication Information
	AuthInfo *string `json:"authInfo,omitempty" tf:"auth_info,omitempty"`

	// Authentication type. anonymous, function, or jwt.
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`
}

type AuthConfigParameters struct {

	// Authentication Information
	// +kubebuilder:validation:Optional
	AuthInfo *string `json:"authInfo,omitempty" tf:"auth_info,omitempty"`

	// Authentication type. anonymous, function, or jwt.
	// +kubebuilder:validation:Optional
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`
}

type CertConfigInitParameters struct {

	// Certificate Name
	CertName *string `json:"certName,omitempty" tf:"cert_name,omitempty"`

	// PEM format certificate
	Certificate *string `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// Private Key in PEM format
	PrivateKeySecretRef *v1.SecretKeySelector `json:"privateKeySecretRef,omitempty" tf:"-"`
}

type CertConfigObservation struct {

	// Certificate Name
	CertName *string `json:"certName,omitempty" tf:"cert_name,omitempty"`

	// PEM format certificate
	Certificate *string `json:"certificate,omitempty" tf:"certificate,omitempty"`
}

type CertConfigParameters struct {

	// Certificate Name
	// +kubebuilder:validation:Optional
	CertName *string `json:"certName,omitempty" tf:"cert_name,omitempty"`

	// PEM format certificate
	// +kubebuilder:validation:Optional
	Certificate *string `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// Private Key in PEM format
	// +kubebuilder:validation:Optional
	PrivateKeySecretRef *v1.SecretKeySelector `json:"privateKeySecretRef,omitempty" tf:"-"`
}

type CustomDomainInitParameters struct {

	// Permission authentication configuration See auth_config below.
	AuthConfig []AuthConfigInitParameters `json:"authConfig,omitempty" tf:"auth_config,omitempty"`

	// HTTPS certificate information See cert_config below.
	CertConfig []CertConfigInitParameters `json:"certConfig,omitempty" tf:"cert_config,omitempty"`

	// The name of the resource
	CustomDomainName *string `json:"customDomainName,omitempty" tf:"custom_domain_name,omitempty"`

	// The protocol type supported by the domain name. HTTP: only HTTP protocol is supported. HTTPS: only HTTPS is supported. HTTP,HTTPS: Supports HTTP and HTTPS protocols.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// Route matching rule configuration See route_config below.
	RouteConfig []RouteConfigInitParameters `json:"routeConfig,omitempty" tf:"route_config,omitempty"`

	// TLS configuration information See tls_config below.
	TLSConfig []TLSConfigInitParameters `json:"tlsConfig,omitempty" tf:"tls_config,omitempty"`

	// Web application firewall configuration information See waf_config below.
	WafConfig []WafConfigInitParameters `json:"wafConfig,omitempty" tf:"waf_config,omitempty"`
}

type CustomDomainObservation struct {

	// (Available since v1.234.0) API version of Function Compute
	APIVersion *string `json:"apiVersion,omitempty" tf:"api_version,omitempty"`

	// (Available since v1.234.0) The ID of your Alibaba Cloud account (primary account).
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Permission authentication configuration See auth_config below.
	AuthConfig []AuthConfigObservation `json:"authConfig,omitempty" tf:"auth_config,omitempty"`

	// HTTPS certificate information See cert_config below.
	CertConfig []CertConfigObservation `json:"certConfig,omitempty" tf:"cert_config,omitempty"`

	// The creation time of the resource
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// The name of the resource
	CustomDomainName *string `json:"customDomainName,omitempty" tf:"custom_domain_name,omitempty"`

	// The ID of the resource supplied above.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Available since v1.234.0) The last time the custom domain name was Updated
	LastModifiedTime *string `json:"lastModifiedTime,omitempty" tf:"last_modified_time,omitempty"`

	// The protocol type supported by the domain name. HTTP: only HTTP protocol is supported. HTTPS: only HTTPS is supported. HTTP,HTTPS: Supports HTTP and HTTPS protocols.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// Route matching rule configuration See route_config below.
	RouteConfig []RouteConfigObservation `json:"routeConfig,omitempty" tf:"route_config,omitempty"`

	// (Available since v1.234.0) Number of subdomains
	SubdomainCount *string `json:"subdomainCount,omitempty" tf:"subdomain_count,omitempty"`

	// TLS configuration information See tls_config below.
	TLSConfig []TLSConfigObservation `json:"tlsConfig,omitempty" tf:"tls_config,omitempty"`

	// Web application firewall configuration information See waf_config below.
	WafConfig []WafConfigObservation `json:"wafConfig,omitempty" tf:"waf_config,omitempty"`
}

type CustomDomainParameters struct {

	// Permission authentication configuration See auth_config below.
	// +kubebuilder:validation:Optional
	AuthConfig []AuthConfigParameters `json:"authConfig,omitempty" tf:"auth_config,omitempty"`

	// HTTPS certificate information See cert_config below.
	// +kubebuilder:validation:Optional
	CertConfig []CertConfigParameters `json:"certConfig,omitempty" tf:"cert_config,omitempty"`

	// The name of the resource
	// +kubebuilder:validation:Optional
	CustomDomainName *string `json:"customDomainName,omitempty" tf:"custom_domain_name,omitempty"`

	// The protocol type supported by the domain name. HTTP: only HTTP protocol is supported. HTTPS: only HTTPS is supported. HTTP,HTTPS: Supports HTTP and HTTPS protocols.
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`

	// Route matching rule configuration See route_config below.
	// +kubebuilder:validation:Optional
	RouteConfig []RouteConfigParameters `json:"routeConfig,omitempty" tf:"route_config,omitempty"`

	// TLS configuration information See tls_config below.
	// +kubebuilder:validation:Optional
	TLSConfig []TLSConfigParameters `json:"tlsConfig,omitempty" tf:"tls_config,omitempty"`

	// Web application firewall configuration information See waf_config below.
	// +kubebuilder:validation:Optional
	WafConfig []WafConfigParameters `json:"wafConfig,omitempty" tf:"waf_config,omitempty"`
}

type EqualRulesInitParameters struct {

	// Matching Rules
	Match *string `json:"match,omitempty" tf:"match,omitempty"`

	// Replace Rules
	Replacement *string `json:"replacement,omitempty" tf:"replacement,omitempty"`
}

type EqualRulesObservation struct {

	// Matching Rules
	Match *string `json:"match,omitempty" tf:"match,omitempty"`

	// Replace Rules
	Replacement *string `json:"replacement,omitempty" tf:"replacement,omitempty"`
}

type EqualRulesParameters struct {

	// Matching Rules
	// +kubebuilder:validation:Optional
	Match *string `json:"match,omitempty" tf:"match,omitempty"`

	// Replace Rules
	// +kubebuilder:validation:Optional
	Replacement *string `json:"replacement,omitempty" tf:"replacement,omitempty"`
}

type RegexRulesInitParameters struct {

	// Matching Rules
	Match *string `json:"match,omitempty" tf:"match,omitempty"`

	// Replace Rules
	Replacement *string `json:"replacement,omitempty" tf:"replacement,omitempty"`
}

type RegexRulesObservation struct {

	// Matching Rules
	Match *string `json:"match,omitempty" tf:"match,omitempty"`

	// Replace Rules
	Replacement *string `json:"replacement,omitempty" tf:"replacement,omitempty"`
}

type RegexRulesParameters struct {

	// Matching Rules
	// +kubebuilder:validation:Optional
	Match *string `json:"match,omitempty" tf:"match,omitempty"`

	// Replace Rules
	// +kubebuilder:validation:Optional
	Replacement *string `json:"replacement,omitempty" tf:"replacement,omitempty"`
}

type RewriteConfigInitParameters struct {

	// Exact Match Rule List See equal_rules below.
	EqualRules []EqualRulesInitParameters `json:"equalRules,omitempty" tf:"equal_rules,omitempty"`

	// Regular match rule list See regex_rules below.
	RegexRules []RegexRulesInitParameters `json:"regexRules,omitempty" tf:"regex_rules,omitempty"`

	// List of wildcard matching rules See wildcard_rules below.
	WildcardRules []WildcardRulesInitParameters `json:"wildcardRules,omitempty" tf:"wildcard_rules,omitempty"`
}

type RewriteConfigObservation struct {

	// Exact Match Rule List See equal_rules below.
	EqualRules []EqualRulesObservation `json:"equalRules,omitempty" tf:"equal_rules,omitempty"`

	// Regular match rule list See regex_rules below.
	RegexRules []RegexRulesObservation `json:"regexRules,omitempty" tf:"regex_rules,omitempty"`

	// List of wildcard matching rules See wildcard_rules below.
	WildcardRules []WildcardRulesObservation `json:"wildcardRules,omitempty" tf:"wildcard_rules,omitempty"`
}

type RewriteConfigParameters struct {

	// Exact Match Rule List See equal_rules below.
	// +kubebuilder:validation:Optional
	EqualRules []EqualRulesParameters `json:"equalRules,omitempty" tf:"equal_rules,omitempty"`

	// Regular match rule list See regex_rules below.
	// +kubebuilder:validation:Optional
	RegexRules []RegexRulesParameters `json:"regexRules,omitempty" tf:"regex_rules,omitempty"`

	// List of wildcard matching rules See wildcard_rules below.
	// +kubebuilder:validation:Optional
	WildcardRules []WildcardRulesParameters `json:"wildcardRules,omitempty" tf:"wildcard_rules,omitempty"`
}

type RouteConfigInitParameters struct {

	// Routing Configuration List See routes below.
	Routes []RoutesInitParameters `json:"routes,omitempty" tf:"routes,omitempty"`
}

type RouteConfigObservation struct {

	// Routing Configuration List See routes below.
	Routes []RoutesObservation `json:"routes,omitempty" tf:"routes,omitempty"`
}

type RouteConfigParameters struct {

	// Routing Configuration List See routes below.
	// +kubebuilder:validation:Optional
	Routes []RoutesParameters `json:"routes,omitempty" tf:"routes,omitempty"`
}

type RoutesInitParameters struct {

	// Function name
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/fcv3/v1alpha1.Function
	FunctionName *string `json:"functionName,omitempty" tf:"function_name,omitempty"`

	// Reference to a Function in fcv3 to populate functionName.
	// +kubebuilder:validation:Optional
	FunctionNameRef *v1.Reference `json:"functionNameRef,omitempty" tf:"-"`

	// Selector for a Function in fcv3 to populate functionName.
	// +kubebuilder:validation:Optional
	FunctionNameSelector *v1.Selector `json:"functionNameSelector,omitempty" tf:"-"`

	// List of supported HTTP methods
	Methods []*string `json:"methods,omitempty" tf:"methods,omitempty"`

	// Route matching rule
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// Version or Alias
	Qualifier *string `json:"qualifier,omitempty" tf:"qualifier,omitempty"`

	// Override Configuration See rewrite_config below.
	RewriteConfig []RewriteConfigInitParameters `json:"rewriteConfig,omitempty" tf:"rewrite_config,omitempty"`
}

type RoutesObservation struct {

	// Function name
	FunctionName *string `json:"functionName,omitempty" tf:"function_name,omitempty"`

	// List of supported HTTP methods
	Methods []*string `json:"methods,omitempty" tf:"methods,omitempty"`

	// Route matching rule
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// Version or Alias
	Qualifier *string `json:"qualifier,omitempty" tf:"qualifier,omitempty"`

	// Override Configuration See rewrite_config below.
	RewriteConfig []RewriteConfigObservation `json:"rewriteConfig,omitempty" tf:"rewrite_config,omitempty"`
}

type RoutesParameters struct {

	// Function name
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/fcv3/v1alpha1.Function
	// +kubebuilder:validation:Optional
	FunctionName *string `json:"functionName,omitempty" tf:"function_name,omitempty"`

	// Reference to a Function in fcv3 to populate functionName.
	// +kubebuilder:validation:Optional
	FunctionNameRef *v1.Reference `json:"functionNameRef,omitempty" tf:"-"`

	// Selector for a Function in fcv3 to populate functionName.
	// +kubebuilder:validation:Optional
	FunctionNameSelector *v1.Selector `json:"functionNameSelector,omitempty" tf:"-"`

	// List of supported HTTP methods
	// +kubebuilder:validation:Optional
	Methods []*string `json:"methods,omitempty" tf:"methods,omitempty"`

	// Route matching rule
	// +kubebuilder:validation:Optional
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// Version or Alias
	// +kubebuilder:validation:Optional
	Qualifier *string `json:"qualifier,omitempty" tf:"qualifier,omitempty"`

	// Override Configuration See rewrite_config below.
	// +kubebuilder:validation:Optional
	RewriteConfig []RewriteConfigParameters `json:"rewriteConfig,omitempty" tf:"rewrite_config,omitempty"`
}

type TLSConfigInitParameters struct {

	// List of TLS cipher suites
	CipherSuites []*string `json:"cipherSuites,omitempty" tf:"cipher_suites,omitempty"`

	// The maximum version of TLS. Enumeration values: TLSv1.3, TLSv1.2, TLSv1.1, TLSv1.0
	MaxVersion *string `json:"maxVersion,omitempty" tf:"max_version,omitempty"`

	// TLS minimum version number. Enumeration values: TLSv1.3, TLSv1.2, TLSv1.1, TLSv1.0
	MinVersion *string `json:"minVersion,omitempty" tf:"min_version,omitempty"`
}

type TLSConfigObservation struct {

	// List of TLS cipher suites
	CipherSuites []*string `json:"cipherSuites,omitempty" tf:"cipher_suites,omitempty"`

	// The maximum version of TLS. Enumeration values: TLSv1.3, TLSv1.2, TLSv1.1, TLSv1.0
	MaxVersion *string `json:"maxVersion,omitempty" tf:"max_version,omitempty"`

	// TLS minimum version number. Enumeration values: TLSv1.3, TLSv1.2, TLSv1.1, TLSv1.0
	MinVersion *string `json:"minVersion,omitempty" tf:"min_version,omitempty"`
}

type TLSConfigParameters struct {

	// List of TLS cipher suites
	// +kubebuilder:validation:Optional
	CipherSuites []*string `json:"cipherSuites,omitempty" tf:"cipher_suites,omitempty"`

	// The maximum version of TLS. Enumeration values: TLSv1.3, TLSv1.2, TLSv1.1, TLSv1.0
	// +kubebuilder:validation:Optional
	MaxVersion *string `json:"maxVersion,omitempty" tf:"max_version,omitempty"`

	// TLS minimum version number. Enumeration values: TLSv1.3, TLSv1.2, TLSv1.1, TLSv1.0
	// +kubebuilder:validation:Optional
	MinVersion *string `json:"minVersion,omitempty" tf:"min_version,omitempty"`
}

type WafConfigInitParameters struct {

	// Enable WAF protection
	EnableWaf *bool `json:"enableWaf,omitempty" tf:"enable_waf,omitempty"`
}

type WafConfigObservation struct {

	// Enable WAF protection
	EnableWaf *bool `json:"enableWaf,omitempty" tf:"enable_waf,omitempty"`
}

type WafConfigParameters struct {

	// Enable WAF protection
	// +kubebuilder:validation:Optional
	EnableWaf *bool `json:"enableWaf,omitempty" tf:"enable_waf,omitempty"`
}

type WildcardRulesInitParameters struct {

	// Matching Rules
	Match *string `json:"match,omitempty" tf:"match,omitempty"`

	// Replace Rules
	Replacement *string `json:"replacement,omitempty" tf:"replacement,omitempty"`
}

type WildcardRulesObservation struct {

	// Matching Rules
	Match *string `json:"match,omitempty" tf:"match,omitempty"`

	// Replace Rules
	Replacement *string `json:"replacement,omitempty" tf:"replacement,omitempty"`
}

type WildcardRulesParameters struct {

	// Matching Rules
	// +kubebuilder:validation:Optional
	Match *string `json:"match,omitempty" tf:"match,omitempty"`

	// Replace Rules
	// +kubebuilder:validation:Optional
	Replacement *string `json:"replacement,omitempty" tf:"replacement,omitempty"`
}

// CustomDomainSpec defines the desired state of CustomDomain
type CustomDomainSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CustomDomainParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CustomDomainInitParameters `json:"initProvider,omitempty"`
}

// CustomDomainStatus defines the observed state of CustomDomain.
type CustomDomainStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CustomDomainObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CustomDomain is the Schema for the CustomDomains API. Provides a Alicloud FCV3 Custom Domain resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type CustomDomain struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              CustomDomainSpec   `json:"spec"`
	Status            CustomDomainStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CustomDomainList contains a list of CustomDomains
type CustomDomainList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CustomDomain `json:"items"`
}

// Repository type metadata.
var (
	CustomDomain_Kind             = "CustomDomain"
	CustomDomain_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CustomDomain_Kind}.String()
	CustomDomain_KindAPIVersion   = CustomDomain_Kind + "." + CRDGroupVersion.String()
	CustomDomain_GroupVersionKind = CRDGroupVersion.WithKind(CustomDomain_Kind)
)

func init() {
	SchemeBuilder.Register(&CustomDomain{}, &CustomDomainList{})
}
