// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Alias) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AsyncInvokeConfig) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ConcurrencyConfig) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CustomDomain) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Function) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *FunctionVersion) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LayerVersion) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProvisionConfig) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Trigger) Hub() {}
