// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type BucketStyleInitParameters struct {

	// Storage space to which the picture style belongs
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-alibabacloud/apis/oss/v1alpha1.Bucket
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// Reference to a Bucket in oss to populate bucket.
	// +kubebuilder:validation:Optional
	BucketRef *v1.Reference `json:"bucketRef,omitempty" tf:"-"`

	// Selector for a Bucket in oss to populate bucket.
	// +kubebuilder:validation:Optional
	BucketSelector *v1.Selector `json:"bucketSelector,omitempty" tf:"-"`

	// Style category, valid values: image, document, video.
	Category *string `json:"category,omitempty" tf:"category,omitempty"`

	// The Image style content can contain single or multiple image processing parameters.
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// Image Style Name
	StyleName *string `json:"styleName,omitempty" tf:"style_name,omitempty"`
}

type BucketStyleObservation struct {

	// Storage space to which the picture style belongs
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// Style category, valid values: image, document, video.
	Category *string `json:"category,omitempty" tf:"category,omitempty"`

	// The Image style content can contain single or multiple image processing parameters.
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// Image Style Creation Time
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// The ID of the resource supplied above.The value is formulated as <bucket>:<style_name>.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Image Style Name
	StyleName *string `json:"styleName,omitempty" tf:"style_name,omitempty"`
}

type BucketStyleParameters struct {

	// Storage space to which the picture style belongs
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-alibabacloud/apis/oss/v1alpha1.Bucket
	// +kubebuilder:validation:Optional
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// Reference to a Bucket in oss to populate bucket.
	// +kubebuilder:validation:Optional
	BucketRef *v1.Reference `json:"bucketRef,omitempty" tf:"-"`

	// Selector for a Bucket in oss to populate bucket.
	// +kubebuilder:validation:Optional
	BucketSelector *v1.Selector `json:"bucketSelector,omitempty" tf:"-"`

	// Style category, valid values: image, document, video.
	// +kubebuilder:validation:Optional
	Category *string `json:"category,omitempty" tf:"category,omitempty"`

	// The Image style content can contain single or multiple image processing parameters.
	// +kubebuilder:validation:Optional
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`

	// Image Style Name
	// +kubebuilder:validation:Optional
	StyleName *string `json:"styleName,omitempty" tf:"style_name,omitempty"`
}

// BucketStyleSpec defines the desired state of BucketStyle
type BucketStyleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     BucketStyleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BucketStyleInitParameters `json:"initProvider,omitempty"`
}

// BucketStyleStatus defines the observed state of BucketStyle.
type BucketStyleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BucketStyleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// BucketStyle is the Schema for the BucketStyles API. Provides a Alicloud OSS Bucket Style resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type BucketStyle struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.content) || (has(self.initProvider) && has(self.initProvider.content))",message="spec.forProvider.content is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.styleName) || (has(self.initProvider) && has(self.initProvider.styleName))",message="spec.forProvider.styleName is a required parameter"
	Spec   BucketStyleSpec   `json:"spec"`
	Status BucketStyleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BucketStyleList contains a list of BucketStyles
type BucketStyleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BucketStyle `json:"items"`
}

// Repository type metadata.
var (
	BucketStyle_Kind             = "BucketStyle"
	BucketStyle_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BucketStyle_Kind}.String()
	BucketStyle_KindAPIVersion   = BucketStyle_Kind + "." + CRDGroupVersion.String()
	BucketStyle_GroupVersionKind = CRDGroupVersion.WithKind(BucketStyle_Kind)
)

func init() {
	SchemeBuilder.Register(&BucketStyle{}, &BucketStyleList{})
}
