// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type BucketRequestPaymentInitParameters struct {

	// The name of the bucket.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-alibabacloud/apis/oss/v1alpha1.Bucket
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// Reference to a Bucket in oss to populate bucket.
	// +kubebuilder:validation:Optional
	BucketRef *v1.Reference `json:"bucketRef,omitempty" tf:"-"`

	// Selector for a Bucket in oss to populate bucket.
	// +kubebuilder:validation:Optional
	BucketSelector *v1.Selector `json:"bucketSelector,omitempty" tf:"-"`

	// The payer of the request and traffic fees.Valid values: BucketOwner: request and traffic fees are paid by the bucket owner. Requester: request and traffic fees are paid by the requester.
	Payer *string `json:"payer,omitempty" tf:"payer,omitempty"`
}

type BucketRequestPaymentObservation struct {

	// The name of the bucket.
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// The ID of the resource supplied above.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The payer of the request and traffic fees.Valid values: BucketOwner: request and traffic fees are paid by the bucket owner. Requester: request and traffic fees are paid by the requester.
	Payer *string `json:"payer,omitempty" tf:"payer,omitempty"`
}

type BucketRequestPaymentParameters struct {

	// The name of the bucket.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-alibabacloud/apis/oss/v1alpha1.Bucket
	// +kubebuilder:validation:Optional
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// Reference to a Bucket in oss to populate bucket.
	// +kubebuilder:validation:Optional
	BucketRef *v1.Reference `json:"bucketRef,omitempty" tf:"-"`

	// Selector for a Bucket in oss to populate bucket.
	// +kubebuilder:validation:Optional
	BucketSelector *v1.Selector `json:"bucketSelector,omitempty" tf:"-"`

	// The payer of the request and traffic fees.Valid values: BucketOwner: request and traffic fees are paid by the bucket owner. Requester: request and traffic fees are paid by the requester.
	// +kubebuilder:validation:Optional
	Payer *string `json:"payer,omitempty" tf:"payer,omitempty"`
}

// BucketRequestPaymentSpec defines the desired state of BucketRequestPayment
type BucketRequestPaymentSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     BucketRequestPaymentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BucketRequestPaymentInitParameters `json:"initProvider,omitempty"`
}

// BucketRequestPaymentStatus defines the observed state of BucketRequestPayment.
type BucketRequestPaymentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BucketRequestPaymentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// BucketRequestPayment is the Schema for the BucketRequestPayments API. Provides a Alicloud OSS Bucket Request Payment resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alicloud}
type BucketRequestPayment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              BucketRequestPaymentSpec   `json:"spec"`
	Status            BucketRequestPaymentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BucketRequestPaymentList contains a list of BucketRequestPayments
type BucketRequestPaymentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BucketRequestPayment `json:"items"`
}

// Repository type metadata.
var (
	BucketRequestPayment_Kind             = "BucketRequestPayment"
	BucketRequestPayment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BucketRequestPayment_Kind}.String()
	BucketRequestPayment_KindAPIVersion   = BucketRequestPayment_Kind + "." + CRDGroupVersion.String()
	BucketRequestPayment_GroupVersionKind = CRDGroupVersion.WithKind(BucketRequestPayment_Kind)
)

func init() {
	SchemeBuilder.Register(&BucketRequestPayment{}, &BucketRequestPaymentList{})
}
