// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AccessPoint) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AccountPublicAccessBlock) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Bucket) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BucketAccessMonitor) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BucketACL) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BucketCname) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BucketCnameToken) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BucketCors) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BucketDataRedundancyTransition) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BucketHTTPSConfig) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BucketLogging) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BucketMetaQuery) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BucketObject) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BucketPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BucketPublicAccessBlock) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BucketReferer) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BucketReplication) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BucketRequestPayment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BucketServerSideEncryption) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BucketStyle) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BucketTransferAcceleration) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BucketUserDefinedLogFields) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BucketVersioning) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BucketWebsite) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BucketWorm) Hub() {}
