// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type VpcEndpointZoneInitParameters struct {

	// Specifies whether to perform only a dry run, without performing the actual request. Valid values:
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	// The endpoint ID.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-alibabacloud/apis/privatelink/v1alpha1.VpcEndpoint
	EndpointID *string `json:"endpointId,omitempty" tf:"endpoint_id,omitempty"`

	// Reference to a VpcEndpoint in privatelink to populate endpointId.
	// +kubebuilder:validation:Optional
	EndpointIDRef *v1.Reference `json:"endpointIdRef,omitempty" tf:"-"`

	// Selector for a VpcEndpoint in privatelink to populate endpointId.
	// +kubebuilder:validation:Optional
	EndpointIDSelector *v1.Selector `json:"endpointIdSelector,omitempty" tf:"-"`

	// The IP address of the endpoint ENI.
	EniIP *string `json:"eniIp,omitempty" tf:"eni_ip,omitempty"`

	// The ID of the vSwitch in the zone.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-alibabacloud/apis/vpc/v1alpha1.Vswitch
	VswitchID *string `json:"vswitchId,omitempty" tf:"vswitch_id,omitempty"`

	// Reference to a Vswitch in vpc to populate vswitchId.
	// +kubebuilder:validation:Optional
	VswitchIDRef *v1.Reference `json:"vswitchIdRef,omitempty" tf:"-"`

	// Selector for a Vswitch in vpc to populate vswitchId.
	// +kubebuilder:validation:Optional
	VswitchIDSelector *v1.Selector `json:"vswitchIdSelector,omitempty" tf:"-"`

	// The zone ID.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type VpcEndpointZoneObservation struct {

	// Specifies whether to perform only a dry run, without performing the actual request. Valid values:
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	// The endpoint ID.
	EndpointID *string `json:"endpointId,omitempty" tf:"endpoint_id,omitempty"`

	// The IP address of the endpoint ENI.
	EniIP *string `json:"eniIp,omitempty" tf:"eni_ip,omitempty"`

	// The ID of the resource supplied above.The value is formulated as <endpoint_id>:<zone_id>.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Available since v1.235.0) The ID of the region to which the endpoint service belongs.
	RegionID *string `json:"regionId,omitempty" tf:"region_id,omitempty"`

	// The state of the zone.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The ID of the vSwitch in the zone.
	VswitchID *string `json:"vswitchId,omitempty" tf:"vswitch_id,omitempty"`

	// The zone ID.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type VpcEndpointZoneParameters struct {

	// Specifies whether to perform only a dry run, without performing the actual request. Valid values:
	// +kubebuilder:validation:Optional
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	// The endpoint ID.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-alibabacloud/apis/privatelink/v1alpha1.VpcEndpoint
	// +kubebuilder:validation:Optional
	EndpointID *string `json:"endpointId,omitempty" tf:"endpoint_id,omitempty"`

	// Reference to a VpcEndpoint in privatelink to populate endpointId.
	// +kubebuilder:validation:Optional
	EndpointIDRef *v1.Reference `json:"endpointIdRef,omitempty" tf:"-"`

	// Selector for a VpcEndpoint in privatelink to populate endpointId.
	// +kubebuilder:validation:Optional
	EndpointIDSelector *v1.Selector `json:"endpointIdSelector,omitempty" tf:"-"`

	// The IP address of the endpoint ENI.
	// +kubebuilder:validation:Optional
	EniIP *string `json:"eniIp,omitempty" tf:"eni_ip,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`

	// The ID of the vSwitch in the zone.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-alibabacloud/apis/vpc/v1alpha1.Vswitch
	// +kubebuilder:validation:Optional
	VswitchID *string `json:"vswitchId,omitempty" tf:"vswitch_id,omitempty"`

	// Reference to a Vswitch in vpc to populate vswitchId.
	// +kubebuilder:validation:Optional
	VswitchIDRef *v1.Reference `json:"vswitchIdRef,omitempty" tf:"-"`

	// Selector for a Vswitch in vpc to populate vswitchId.
	// +kubebuilder:validation:Optional
	VswitchIDSelector *v1.Selector `json:"vswitchIdSelector,omitempty" tf:"-"`

	// The zone ID.
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

// VpcEndpointZoneSpec defines the desired state of VpcEndpointZone
type VpcEndpointZoneSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     VpcEndpointZoneParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VpcEndpointZoneInitParameters `json:"initProvider,omitempty"`
}

// VpcEndpointZoneStatus defines the observed state of VpcEndpointZone.
type VpcEndpointZoneStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VpcEndpointZoneObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// VpcEndpointZone is the Schema for the VpcEndpointZones API. Provides a Alicloud Private Link Vpc Endpoint Zone resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type VpcEndpointZone struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              VpcEndpointZoneSpec   `json:"spec"`
	Status            VpcEndpointZoneStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VpcEndpointZoneList contains a list of VpcEndpointZones
type VpcEndpointZoneList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VpcEndpointZone `json:"items"`
}

// Repository type metadata.
var (
	VpcEndpointZone_Kind             = "VpcEndpointZone"
	VpcEndpointZone_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VpcEndpointZone_Kind}.String()
	VpcEndpointZone_KindAPIVersion   = VpcEndpointZone_Kind + "." + CRDGroupVersion.String()
	VpcEndpointZone_GroupVersionKind = CRDGroupVersion.WithKind(VpcEndpointZone_Kind)
)

func init() {
	SchemeBuilder.Register(&VpcEndpointZone{}, &VpcEndpointZoneList{})
}
