// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type SecurityPreferenceInitParameters struct {

	// Specifies whether RAM users can change their passwords. Valid values: true and false
	AllowUserToChangePassword *bool `json:"allowUserToChangePassword,omitempty" tf:"allow_user_to_change_password,omitempty"`

	// Specifies whether RAM users can manage their AccessKey pairs. Valid values: true and false
	AllowUserToManageAccessKeys *bool `json:"allowUserToManageAccessKeys,omitempty" tf:"allow_user_to_manage_access_keys,omitempty"`

	// Specifies whether RAM users can manage their MFA devices. Valid values: true and false
	AllowUserToManageMfaDevices *bool `json:"allowUserToManageMfaDevices,omitempty" tf:"allow_user_to_manage_mfa_devices,omitempty"`

	// Specifies whether to remember the MFA devices for seven days. Valid values: true and false
	EnableSaveMfaTicket *bool `json:"enableSaveMfaTicket,omitempty" tf:"enable_save_mfa_ticket,omitempty"`

	// Specifies whether MFA is required for all RAM users when they log on to the Alibaba Cloud Management Console by using usernames and passwords. Valid values: true and false
	EnforceMfaForLogin *bool `json:"enforceMfaForLogin,omitempty" tf:"enforce_mfa_for_login,omitempty"`

	// The subnet mask that specifies the IP addresses from which you can log on to the Alibaba Cloud Management Console. This parameter takes effect on password-based logon and single sign-on (SSO). However, this parameter does not take effect on API calls that are authenticated by using AccessKey pairs.NOTE: You can specify up to 25 subnet masks. The total length of the subnet masks can be a maximum of 512 characters.
	LoginNetworkMasks *string `json:"loginNetworkMasks,omitempty" tf:"login_network_masks,omitempty"`

	// The validity period of the logon session of RAM users. Valid values: 6 to 24. Unit: hours. Default value: 6.
	LoginSessionDuration *float64 `json:"loginSessionDuration,omitempty" tf:"login_session_duration,omitempty"`
}

type SecurityPreferenceObservation struct {

	// Specifies whether RAM users can change their passwords. Valid values: true and false
	AllowUserToChangePassword *bool `json:"allowUserToChangePassword,omitempty" tf:"allow_user_to_change_password,omitempty"`

	// Specifies whether RAM users can manage their AccessKey pairs. Valid values: true and false
	AllowUserToManageAccessKeys *bool `json:"allowUserToManageAccessKeys,omitempty" tf:"allow_user_to_manage_access_keys,omitempty"`

	// Specifies whether RAM users can manage their MFA devices. Valid values: true and false
	AllowUserToManageMfaDevices *bool `json:"allowUserToManageMfaDevices,omitempty" tf:"allow_user_to_manage_mfa_devices,omitempty"`

	// Specifies whether to remember the MFA devices for seven days. Valid values: true and false
	EnableSaveMfaTicket *bool `json:"enableSaveMfaTicket,omitempty" tf:"enable_save_mfa_ticket,omitempty"`

	// Specifies whether MFA is required for all RAM users when they log on to the Alibaba Cloud Management Console by using usernames and passwords. Valid values: true and false
	EnforceMfaForLogin *bool `json:"enforceMfaForLogin,omitempty" tf:"enforce_mfa_for_login,omitempty"`

	// The ID is set as RamSecurityPreference.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The subnet mask that specifies the IP addresses from which you can log on to the Alibaba Cloud Management Console. This parameter takes effect on password-based logon and single sign-on (SSO). However, this parameter does not take effect on API calls that are authenticated by using AccessKey pairs.NOTE: You can specify up to 25 subnet masks. The total length of the subnet masks can be a maximum of 512 characters.
	LoginNetworkMasks *string `json:"loginNetworkMasks,omitempty" tf:"login_network_masks,omitempty"`

	// The validity period of the logon session of RAM users. Valid values: 6 to 24. Unit: hours. Default value: 6.
	LoginSessionDuration *float64 `json:"loginSessionDuration,omitempty" tf:"login_session_duration,omitempty"`
}

type SecurityPreferenceParameters struct {

	// Specifies whether RAM users can change their passwords. Valid values: true and false
	// +kubebuilder:validation:Optional
	AllowUserToChangePassword *bool `json:"allowUserToChangePassword,omitempty" tf:"allow_user_to_change_password,omitempty"`

	// Specifies whether RAM users can manage their AccessKey pairs. Valid values: true and false
	// +kubebuilder:validation:Optional
	AllowUserToManageAccessKeys *bool `json:"allowUserToManageAccessKeys,omitempty" tf:"allow_user_to_manage_access_keys,omitempty"`

	// Specifies whether RAM users can manage their MFA devices. Valid values: true and false
	// +kubebuilder:validation:Optional
	AllowUserToManageMfaDevices *bool `json:"allowUserToManageMfaDevices,omitempty" tf:"allow_user_to_manage_mfa_devices,omitempty"`

	// Specifies whether to remember the MFA devices for seven days. Valid values: true and false
	// +kubebuilder:validation:Optional
	EnableSaveMfaTicket *bool `json:"enableSaveMfaTicket,omitempty" tf:"enable_save_mfa_ticket,omitempty"`

	// Specifies whether MFA is required for all RAM users when they log on to the Alibaba Cloud Management Console by using usernames and passwords. Valid values: true and false
	// +kubebuilder:validation:Optional
	EnforceMfaForLogin *bool `json:"enforceMfaForLogin,omitempty" tf:"enforce_mfa_for_login,omitempty"`

	// The subnet mask that specifies the IP addresses from which you can log on to the Alibaba Cloud Management Console. This parameter takes effect on password-based logon and single sign-on (SSO). However, this parameter does not take effect on API calls that are authenticated by using AccessKey pairs.NOTE: You can specify up to 25 subnet masks. The total length of the subnet masks can be a maximum of 512 characters.
	// +kubebuilder:validation:Optional
	LoginNetworkMasks *string `json:"loginNetworkMasks,omitempty" tf:"login_network_masks,omitempty"`

	// The validity period of the logon session of RAM users. Valid values: 6 to 24. Unit: hours. Default value: 6.
	// +kubebuilder:validation:Optional
	LoginSessionDuration *float64 `json:"loginSessionDuration,omitempty" tf:"login_session_duration,omitempty"`
}

// SecurityPreferenceSpec defines the desired state of SecurityPreference
type SecurityPreferenceSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SecurityPreferenceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SecurityPreferenceInitParameters `json:"initProvider,omitempty"`
}

// SecurityPreferenceStatus defines the observed state of SecurityPreference.
type SecurityPreferenceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SecurityPreferenceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SecurityPreference is the Schema for the SecurityPreferences API. Provides a Alicloud RAM Security Preference resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type SecurityPreference struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SecurityPreferenceSpec   `json:"spec"`
	Status            SecurityPreferenceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SecurityPreferenceList contains a list of SecurityPreferences
type SecurityPreferenceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SecurityPreference `json:"items"`
}

// Repository type metadata.
var (
	SecurityPreference_Kind             = "SecurityPreference"
	SecurityPreference_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SecurityPreference_Kind}.String()
	SecurityPreference_KindAPIVersion   = SecurityPreference_Kind + "." + CRDGroupVersion.String()
	SecurityPreference_GroupVersionKind = CRDGroupVersion.WithKind(SecurityPreference_Kind)
)

func init() {
	SchemeBuilder.Register(&SecurityPreference{}, &SecurityPreferenceList{})
}
