apiVersion: alb.alibabacloud.crossplane.io/v1alpha1
kind: Listener
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/listener
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    defaultActions:
    - forwardGroupConfig:
      - serverGroupTuples:
        - serverGroupIdSelector:
            matchLabels:
              testing.upbound.io/example-name: for-listener
      type: ForwardGroup
    listenerDescription: crossplane-example
    listenerPort: 443
    listenerProtocol: HTTP
    loadBalancerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: for-listener
    region: cn-beijing

---

apiVersion: alb.alibabacloud.crossplane.io/v1alpha1
kind: LoadBalancer
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/listener
  labels:
    testing.upbound.io/example-name: for-listener
  name: for-listener
spec:
  forProvider:
    addressAllocatedMode: Fixed
    addressType: Internet
    loadBalancerBillingConfig:
    - payType: PayAsYouGo
    loadBalancerEdition: Basic
    loadBalancerName: crossplane-example
    modificationProtectionConfig:
    - status: NonProtection
    region: cn-beijing
#    resourceGroupId: ${data.alicloud_resource_manager_resource_groups.default.groups.0.id}
    tags:
      Created: TF
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: for-listener
    zoneMappings:
    - vswitchIdSelector:
        matchLabels:
          testing.upbound.io/example-name: for-listener-1
      zoneId: cn-beijing-f
    - vswitchIdSelector:
        matchLabels:
          testing.upbound.io/example-name: for-listener-2
      zoneId: cn-beijing-g

---

apiVersion: alb.alibabacloud.crossplane.io/v1alpha1
kind: ServerGroup
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/listener
  labels:
    testing.upbound.io/example-name: for-listener
  name: for-listener
spec:
  forProvider:
    healthCheckConfig:
    - healthCheckCodes:
      - http_2xx
      - http_3xx
      - http_4xx
      healthCheckConnectPort: 46325
      healthCheckEnabled: true
      healthCheckHost: tf-example.com
      healthCheckHttpVersion: HTTP1.1
      healthCheckInterval: 2
      healthCheckMethod: HEAD
      healthCheckPath: /tf-example
      healthCheckProtocol: HTTP
      healthCheckTimeout: 5
      healthyThreshold: 3
      unhealthyThreshold: 3
    protocol: HTTP
    region: cn-beijing
#    resourceGroupId: ${data.alicloud_resource_manager_resource_groups.default.groups.0.id}
    serverGroupName: crossplane-example
    servers:
    - description: crossplane-example
      port: 80
      serverIdSelector:
        matchLabels:
          testing.upbound.io/example-name: for-listener
      serverIpSelector:
        matchLabels:
          testing.upbound.io/example-name: for-listener
      serverType: Ecs
      weight: 10
    stickySessionConfig:
    - cookie: tf-example
      stickySessionEnabled: true
      stickySessionType: Server
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: for-listener

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/listener
  labels:
    testing.upbound.io/example-name: for-listener
  name: for-listener
spec:
  forProvider:
    availabilityZone: cn-beijing-f
    imageId: ubuntu_18_04_x64_20G_alibase_20240223.vhd
    instanceName: crossplane-example
    instanceType: ecs.sn1ne.large
    region: cn-beijing
    securityGroupRefs:
    - name: for-listener
    vswitchIdSelector:
      matchLabels:
        testing.upbound.io/example-name: for-listener-1

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/listener
  labels:
    testing.upbound.io/example-name: for-listener
  name: for-listener
spec:
  forProvider:
    description: crossplane-example
    region: cn-beijing
    securityGroupName: crossplane-example
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: for-listener

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/listener
  labels:
    testing.upbound.io/example-name: for-listener
  name: for-listener
spec:
  forProvider:
    cidrBlock: 10.4.0.0/16
    region: cn-beijing
    vpcName: crossplane-example

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/listener
  labels:
    testing.upbound.io/example-name: for-listener-1
  name: for-listener-1
spec:
  forProvider:
    cidrBlock: 10.4.1.0/24
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: for-listener
    vswitchName: crossplane-example_1
    zoneId: cn-beijing-f

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/listener
  labels:
    testing.upbound.io/example-name: for-listener-2
  name: for-listener-2
spec:
  forProvider:
    cidrBlock: 10.4.2.0/24
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: for-listener
    vswitchName: crossplane-example_2
    zoneId: cn-beijing-g
