apiVersion: ram.alibabacloud.crossplane.io/v1alpha1
kind: RolePolicyAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: ram/v1alpha1/rolepolicyattachment
  labels:
    testing.upbound.io/example-name: attach
  name: attach
spec:
  forProvider:
    policyNameSelector:
      matchLabels:
        testing.upbound.io/example-name: policy
    policyTypeSelector:
      matchLabels:
        testing.upbound.io/example-name: policy
    roleNameSelector:
      matchLabels:
        testing.upbound.io/example-name: role

---

apiVersion: ram.alibabacloud.crossplane.io/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: ram/v1alpha1/rolepolicyattachment
  labels:
    testing.upbound.io/example-name: policy
  name: policy
spec:
  forProvider:
    description: this is a policy test
    policyDocument: |2
        {
          "Statement": [
            {
              "Action": [
                "oss:ListObjects",
                "oss:GetObject"
              ],
              "Effect": "Allow",
              "Resource": [
                "acs:oss:*:*:mybucket",
                "acs:oss:*:*:mybucket/*"
              ]
            }
          ],
            "Version": "1"
        }
    policyName: tf-example-${random_integer.default.result}

---

apiVersion: ram.alibabacloud.crossplane.io/v1alpha1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: ram/v1alpha1/rolepolicyattachment
  labels:
    testing.upbound.io/example-name: role
  name: role
spec:
  forProvider:
    description: this is a role test.
    document: "    {\n      \"Statement\": [\n        {\n          \"Action\": \"sts:AssumeRole\",\n
      \         \"Effect\": \"Allow\",\n          \"Principal\": {\n            \"Service\":
      [\n              \"apigateway.aliyuncs.com\", \n              \"ecs.aliyuncs.com\"\n
      \           ]\n          }\n        }\n      ],\n      \"Version\": \"1\"\n
      \   }\n"
    name: roleName
