---
apiVersion: ackone.alibabacloud.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: test-ackone-v1alpha1-cluster-1
    crossplane.io/external-name: test-ackone-v1alpha1-cluster-1
  labels:
    testing.upbound.io/example-name: test-ackone-v1alpha1-cluster-1
  name: test-ackone-v1alpha1-cluster-1
spec:
  forProvider:
    network:
      - vpcIdSelector:
          matchLabels:
            testing.upbound.io/example-name: test-ackone-v1alpha1-cluster-1-vpc
        vswitchesSelector:
          matchLabels:
            testing.upbound.io/example-name: test-ackone-v1alpha1-cluster-1-vswitch
    profile: Default
---
apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: test-ackone-v1alpha1-cluster-1-vpc
  labels:
    testing.upbound.io/example-name: test-ackone-v1alpha1-cluster-1-vpc
  name: test-ackone-v1alpha1-cluster-1-vpc
spec:
  forProvider:
    cidrBlock: 172.16.0.0/12
    vpcName: test-ackone-v1alpha1-cluster-1-vpc
---
apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: test-ackone-v1alpha1-cluster-1-vswitch
    crossplane.io/external-name: test-ackone-v1alpha1-cluster-1-vswitch
  labels:
    testing.upbound.io/example-name: test-ackone-v1alpha1-cluster-1-vswitch
  name: test-ackone-v1alpha1-cluster-1-vswitch
spec:
  forProvider:
    cidrBlock: 172.16.2.0/24
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test-ackone-v1alpha1-cluster-1-vpc
    vswitchName: test-ackone-v1alpha1-cluster-1-vswitch
    zoneId: cn-beijing-h
