// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type MembershipAttachmentInitParameters struct {

	// The ID of the cluster to which the membership is being attached.
	// ID of the ACK One fleet cluster
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-alibabacloud/apis/ackone/v1alpha1.Cluster
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in ackone to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in ackone to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// The ID of the member being attached to the cluster.
	// ID of the ACK cluster that needs to be managed by ACK One fleet
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-alibabacloud/apis/ack/v1alpha1.ManagedKubernetes
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	SubClusterID *string `json:"subClusterId,omitempty" tf:"sub_cluster_id,omitempty"`

	// Reference to a ManagedKubernetes in ack to populate subClusterId.
	// +kubebuilder:validation:Optional
	SubClusterIDRef *v1.Reference `json:"subClusterIdRef,omitempty" tf:"-"`

	// Selector for a ManagedKubernetes in ack to populate subClusterId.
	// +kubebuilder:validation:Optional
	SubClusterIDSelector *v1.Selector `json:"subClusterIdSelector,omitempty" tf:"-"`
}

type MembershipAttachmentObservation struct {

	// The ID of the cluster to which the membership is being attached.
	// ID of the ACK One fleet cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// It formats as < cluster_id >:< sub_cluster_id >.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the member being attached to the cluster.
	// ID of the ACK cluster that needs to be managed by ACK One fleet
	SubClusterID *string `json:"subClusterId,omitempty" tf:"sub_cluster_id,omitempty"`
}

type MembershipAttachmentParameters struct {

	// The ID of the cluster to which the membership is being attached.
	// ID of the ACK One fleet cluster
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-alibabacloud/apis/ackone/v1alpha1.Cluster
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in ackone to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in ackone to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`

	// The ID of the member being attached to the cluster.
	// ID of the ACK cluster that needs to be managed by ACK One fleet
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-alibabacloud/apis/ack/v1alpha1.ManagedKubernetes
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	SubClusterID *string `json:"subClusterId,omitempty" tf:"sub_cluster_id,omitempty"`

	// Reference to a ManagedKubernetes in ack to populate subClusterId.
	// +kubebuilder:validation:Optional
	SubClusterIDRef *v1.Reference `json:"subClusterIdRef,omitempty" tf:"-"`

	// Selector for a ManagedKubernetes in ack to populate subClusterId.
	// +kubebuilder:validation:Optional
	SubClusterIDSelector *v1.Selector `json:"subClusterIdSelector,omitempty" tf:"-"`
}

// MembershipAttachmentSpec defines the desired state of MembershipAttachment
type MembershipAttachmentSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     MembershipAttachmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MembershipAttachmentInitParameters `json:"initProvider,omitempty"`
}

// MembershipAttachmentStatus defines the observed state of MembershipAttachment.
type MembershipAttachmentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MembershipAttachmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MembershipAttachment is the Schema for the MembershipAttachments API. Provides a Alicloud Ack One Membership Attachment resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type MembershipAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              MembershipAttachmentSpec   `json:"spec"`
	Status            MembershipAttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MembershipAttachmentList contains a list of MembershipAttachments
type MembershipAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MembershipAttachment `json:"items"`
}

// Repository type metadata.
var (
	MembershipAttachment_Kind             = "MembershipAttachment"
	MembershipAttachment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MembershipAttachment_Kind}.String()
	MembershipAttachment_KindAPIVersion   = MembershipAttachment_Kind + "." + CRDGroupVersion.String()
	MembershipAttachment_GroupVersionKind = CRDGroupVersion.WithKind(MembershipAttachment_Kind)
)

func init() {
	SchemeBuilder.Register(&MembershipAttachment{}, &MembershipAttachmentList{})
}
