// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AlarmContactGroupInitParameters struct {

	// The name of the alarm group.
	AlarmContactGroupName *string `json:"alarmContactGroupName,omitempty" tf:"alarm_contact_group_name,omitempty"`

	// The name of the alert contact.
	// +listType=set
	Contacts []*string `json:"contacts,omitempty" tf:"contacts,omitempty"`

	// The description of the alert group.
	Describe *string `json:"describe,omitempty" tf:"describe,omitempty"`

	// Whether to open weekly subscription.
	EnableSubscribed *bool `json:"enableSubscribed,omitempty" tf:"enable_subscribed,omitempty"`
}

type AlarmContactGroupObservation struct {

	// The name of the alarm group.
	AlarmContactGroupName *string `json:"alarmContactGroupName,omitempty" tf:"alarm_contact_group_name,omitempty"`

	// The name of the alert contact.
	// +listType=set
	Contacts []*string `json:"contacts,omitempty" tf:"contacts,omitempty"`

	// The description of the alert group.
	Describe *string `json:"describe,omitempty" tf:"describe,omitempty"`

	// Whether to open weekly subscription.
	EnableSubscribed *bool `json:"enableSubscribed,omitempty" tf:"enable_subscribed,omitempty"`

	// The resource ID of Alarm Contact Group.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type AlarmContactGroupParameters struct {

	// The name of the alarm group.
	// +kubebuilder:validation:Optional
	AlarmContactGroupName *string `json:"alarmContactGroupName,omitempty" tf:"alarm_contact_group_name,omitempty"`

	// The name of the alert contact.
	// +kubebuilder:validation:Optional
	// +listType=set
	Contacts []*string `json:"contacts,omitempty" tf:"contacts,omitempty"`

	// The description of the alert group.
	// +kubebuilder:validation:Optional
	Describe *string `json:"describe,omitempty" tf:"describe,omitempty"`

	// Whether to open weekly subscription.
	// +kubebuilder:validation:Optional
	EnableSubscribed *bool `json:"enableSubscribed,omitempty" tf:"enable_subscribed,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`
}

// AlarmContactGroupSpec defines the desired state of AlarmContactGroup
type AlarmContactGroupSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AlarmContactGroupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AlarmContactGroupInitParameters `json:"initProvider,omitempty"`
}

// AlarmContactGroupStatus defines the observed state of AlarmContactGroup.
type AlarmContactGroupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AlarmContactGroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AlarmContactGroup is the Schema for the AlarmContactGroups API. Provides a Alicloud CMS Alarm Contact Group resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type AlarmContactGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.alarmContactGroupName) || (has(self.initProvider) && has(self.initProvider.alarmContactGroupName))",message="spec.forProvider.alarmContactGroupName is a required parameter"
	Spec   AlarmContactGroupSpec   `json:"spec"`
	Status AlarmContactGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AlarmContactGroupList contains a list of AlarmContactGroups
type AlarmContactGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AlarmContactGroup `json:"items"`
}

// Repository type metadata.
var (
	AlarmContactGroup_Kind             = "AlarmContactGroup"
	AlarmContactGroup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AlarmContactGroup_Kind}.String()
	AlarmContactGroup_KindAPIVersion   = AlarmContactGroup_Kind + "." + CRDGroupVersion.String()
	AlarmContactGroup_GroupVersionKind = CRDGroupVersion.WithKind(AlarmContactGroup_Kind)
)

func init() {
	SchemeBuilder.Register(&AlarmContactGroup{}, &AlarmContactGroupList{})
}
