// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AclEntryAttachmentInitParameters struct {

	// The ID of the Acl.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-alibabacloud/apis/alb/v1alpha1.Acl
	ACLID *string `json:"aclId,omitempty" tf:"acl_id,omitempty"`

	// Reference to a Acl in alb to populate aclId.
	// +kubebuilder:validation:Optional
	ACLIDRef *v1.Reference `json:"aclIdRef,omitempty" tf:"-"`

	// Selector for a Acl in alb to populate aclId.
	// +kubebuilder:validation:Optional
	ACLIDSelector *v1.Selector `json:"aclIdSelector,omitempty" tf:"-"`

	// The description of the entry.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The CIDR blocks.
	Entry *string `json:"entry,omitempty" tf:"entry,omitempty"`
}

type AclEntryAttachmentObservation struct {

	// The ID of the Acl.
	ACLID *string `json:"aclId,omitempty" tf:"acl_id,omitempty"`

	// The description of the entry.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The CIDR blocks.
	Entry *string `json:"entry,omitempty" tf:"entry,omitempty"`

	// The ID of the resource. The value formats as <acl_id>:<entry>.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The Status of the resource.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type AclEntryAttachmentParameters struct {

	// The ID of the Acl.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-alibabacloud/apis/alb/v1alpha1.Acl
	// +kubebuilder:validation:Optional
	ACLID *string `json:"aclId,omitempty" tf:"acl_id,omitempty"`

	// Reference to a Acl in alb to populate aclId.
	// +kubebuilder:validation:Optional
	ACLIDRef *v1.Reference `json:"aclIdRef,omitempty" tf:"-"`

	// Selector for a Acl in alb to populate aclId.
	// +kubebuilder:validation:Optional
	ACLIDSelector *v1.Selector `json:"aclIdSelector,omitempty" tf:"-"`

	// The description of the entry.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The CIDR blocks.
	// +kubebuilder:validation:Optional
	Entry *string `json:"entry,omitempty" tf:"entry,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`
}

// AclEntryAttachmentSpec defines the desired state of AclEntryAttachment
type AclEntryAttachmentSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AclEntryAttachmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AclEntryAttachmentInitParameters `json:"initProvider,omitempty"`
}

// AclEntryAttachmentStatus defines the observed state of AclEntryAttachment.
type AclEntryAttachmentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AclEntryAttachmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AclEntryAttachment is the Schema for the AclEntryAttachments API. Provides a Acl entry attachment resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type AclEntryAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.entry) || (has(self.initProvider) && has(self.initProvider.entry))",message="spec.forProvider.entry is a required parameter"
	Spec   AclEntryAttachmentSpec   `json:"spec"`
	Status AclEntryAttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AclEntryAttachmentList contains a list of AclEntryAttachments
type AclEntryAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AclEntryAttachment `json:"items"`
}

// Repository type metadata.
var (
	AclEntryAttachment_Kind             = "AclEntryAttachment"
	AclEntryAttachment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AclEntryAttachment_Kind}.String()
	AclEntryAttachment_KindAPIVersion   = AclEntryAttachment_Kind + "." + CRDGroupVersion.String()
	AclEntryAttachment_GroupVersionKind = CRDGroupVersion.WithKind(AclEntryAttachment_Kind)
)

func init() {
	SchemeBuilder.Register(&AclEntryAttachment{}, &AclEntryAttachmentList{})
}
