// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Acl) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AclEntryAttachment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Ascript) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *HealthCheckTemplate) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Listener) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ListenerAclAttachment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LoadBalancer) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LoadBalancerSecurityGroupAttachment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LoadBalancerZoneShiftedAttachment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Rule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SecurityPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ServerGroup) Hub() {}
