---
# NAME                                                                            SYNCED   READY   EXTERNAL-NAME                       AGE
# autoscalingconfig.ack.alibabacloud.crossplane.io/test-ack-v1alpha1-asc-1        True     True    c02322f5d7bf045788922100672f23713   12m
# managedkubernetes.ack.alibabacloud.crossplane.io/test-ack-v1alpha1-asc-mk8s-1   True     True    c02322f5d7bf045788922100672f23713   12m
# vpc.vpc.alibabacloud.crossplane.io/test-ack-v1alpha1-asc-vpc-1                  True     True    vpc-rj9ivwmiya4e631ajvsad   12m
# vswitch.vpc.alibabacloud.crossplane.io/test-ack-v1alpha1-asc-vswitch-1          True     True    vsw-rj9whbvwmaiip5w99zyds   12m
#
apiVersion: ack.alibabacloud.crossplane.io/v1alpha1
kind: AutoscalingConfig
metadata:
  annotations:
    meta.upbound.io/example-id: test-ack-v1alpha1-asc-1
  labels:
    testing.upbound.io/example-name: test-ack-v1alpha1-asc-1
  name: test-ack-v1alpha1-asc-1
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test-ack-v1alpha1-asc-mk8s-1
    coolDownDuration: 10m
    daemonsetEvictionForNodes: false
    expander: least-waste
    gpuUtilizationThreshold: "0.5"
    maxGracefulTerminationSec: 14400
    minReplicaCount: 0
    recycleNodeDeletionEnabled: false
    scaleDownEnabled: true
    scaleUpFromZero: true
    scalerType: goatscaler
    scanInterval: 30s
    skipNodesWithLocalStorage: false
    skipNodesWithSystemPods: true
    unneededDuration: 10m
    utilizationThreshold: "0.5"
---
apiVersion: ack.alibabacloud.crossplane.io/v1alpha1
kind: ManagedKubernetes
metadata:
  annotations:
    meta.upbound.io/example-id: test-ack-v1alpha1-asc-mk8s-1
    uptest.upbound.io/timeout: "2400"
  labels:
    testing.upbound.io/example-name: test-ack-v1alpha1-asc-mk8s-1
  name: test-ack-v1alpha1-asc-mk8s-1
spec:
  forProvider:
    clusterSpec: ack.pro.small
    newNatGateway: true
    podCidr: 10.0.0.0/16
    serviceCidr: 172.16.0.0/20
    slbInternetEnabled: true
    vswitchIdsSelector:
      matchLabels:
        testing.upbound.io/example-name: test-ack-v1alpha1-asc-vswitch-1
---
apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: test-ack-v1alpha1-asc-vpc-1
  labels:
    testing.upbound.io/example-name: test-ack-v1alpha1-asc-vpc-1
  name: test-ack-v1alpha1-asc-vpc-1
spec:
  forProvider:
    cidrBlock: 10.4.0.0/16
    vpcName: test-ack-v1alpha1-asc-vpc-1
---
apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: test-ack-v1alpha1-asc-vswitch-1
  labels:
    testing.upbound.io/example-name: test-ack-v1alpha1-asc-vswitch-1
  name: test-ack-v1alpha1-asc-vswitch-1
spec:
  forProvider:
    cidrBlock: 10.4.0.0/24
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test-ack-v1alpha1-asc-vpc-1
    vswitchName: test-ack-v1alpha1-asc-vswitch-1
    zoneId: us-west-1b
#---
# The Role below may be needed if permissions are not yet specified.
#
#apiVersion: ram.alibabacloud.crossplane.io/v1alpha1
#kind: Role
#metadata:
#  annotations:
#    meta.crossplane.io/example-id: aliyuncsdefaultrole
#  labels:
#    testing.crossplane.io/example-name: aliyuncsdefaultrole
#  name: aliyuncsdefaultrole
#spec:
#  forProvider:
#    description: aliyuncsdefaultrole
#    document: |
#      {
#          "Statement": [
#              {
#                  "Action": "sts:AssumeRole",
#                  "Effect": "Allow",
#                  "Principal": {
#                      "Service": [
#                          "cs.aliyuncs.com",
#                          "ecs.aliyuncs.com",
#                          "kms.aliyuncs.com",
#                          "oss.aliyuncs.com",
#                          "vpc.aliyuncs.com"
#                      ]
#                  }
#              }
#          ],
#          "Version": "1"
#      }
#    name: aliyuncsdefaultrole
