---
#
# NAME                                                                                          SYNCED   READY   EXTERNAL-NAME        AGE
# kubernetespermissions.ack.alibabacloud.crossplane.io/test-ack-v1alpha1-k8spermissions-1       True     True    213773948999939583   14m
# managedkubernetes.ack.alibabacloud.crossplane.io/test-ack-v1alpha1-k8spermissions-cluster-1   True     True    c821d0edb3ba54155b07bcdb06794d672   14m
# user.ram.alibabacloud.crossplane.io/test-ack-v1alpha1-k8spermissions-user-1                   True     True    213773948999939583   14m
# vpc.vpc.alibabacloud.crossplane.io/test-ack-v1alpha1-k8spermissions-vpc-1                     True     True    vpc-rj9fysh5rg1u3bczi35l1   14m
# vswitch.vpc.alibabacloud.crossplane.io/test-ack-v1alpha1-k8spermissions-vsw-1                 True     True    vsw-rj9qqpjs3akg7ou6yvqoz   14m
#
# PASS
# 18:38:51 [ OK ] running automated tests
#
apiVersion: ack.alibabacloud.crossplane.io/v1alpha1
kind: KubernetesPermissions
metadata:
  annotations:
    meta.upbound.io/example-id: test-ack-v1alpha1-k8spermissions-1
  labels:
    testing.upbound.io/example-name: test-ack-v1alpha1-k8spermissions-1
  name: test-ack-v1alpha1-k8spermissions-1
spec:
  forProvider:
    permissions:
    - clusterIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test-ack-v1alpha1-k8spermissions-cluster-1
      isCustom: false
      isRamRole: false
      namespace: ""
      roleName: admin
      roleType: cluster
    uidSelector:
      matchLabels:
        testing.upbound.io/example-name: test-ack-v1alpha1-k8spermissions-user-1
---
apiVersion: ack.alibabacloud.crossplane.io/v1alpha1
kind: ManagedKubernetes
metadata:
  annotations:
    meta.upbound.io/example-id: test-ack-v1alpha1-k8spermissions-cluster-1
    uptest.upbound.io/timeout: "2400"
  labels:
    testing.upbound.io/example-name: test-ack-v1alpha1-k8spermissions-cluster-1
  name: test-ack-v1alpha1-k8spermissions-cluster-1
spec:
  forProvider:
    clusterSpec: ack.pro.small
    name: test-ack-v1alpha1-k8spermissions-cluster-1
    newNatGateway: false
    podCidr: 10.32.0.0/27
    serviceCidr: 172.20.0.0/23
    slbInternetEnabled: false
    workerVswitchIdsSelector:
      matchLabels:
        testing.upbound.io/example-name: test-ack-v1alpha1-k8spermissions-vsw-1
---
apiVersion: ram.alibabacloud.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: test-ack-v1alpha1-k8spermissions-user-1
  labels:
    testing.upbound.io/example-name: test-ack-v1alpha1-k8spermissions-user-1
  name: test-ack-v1alpha1-k8spermissions-user-1
spec:
  forProvider:
    name: test-ack-v1alpha1-k8spermissions-user-1
---
apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: test-ack-v1alpha1-k8spermissions-vpc-1
  labels:
    testing.upbound.io/example-name: test-ack-v1alpha1-k8spermissions-vpc-1
  name: test-ack-v1alpha1-k8spermissions-vpc-1
spec:
  forProvider:
    cidrBlock: 10.4.0.0/16
    vpcName: test-ack-v1alpha1-k8spermissions-vpc-1
---
apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: test-ack-v1alpha1-k8spermissions-vsw-1
  labels:
    testing.upbound.io/example-name: test-ack-v1alpha1-k8spermissions-vsw-1
  name: test-ack-v1alpha1-k8spermissions-vsw-1
spec:
  forProvider:
    cidrBlock: 10.4.0.0/24
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test-ack-v1alpha1-k8spermissions-vpc-1
    vswitchName: test-ack-v1alpha1-k8spermissions-vsw-1
    zoneId: us-west-1a
