apiVersion: alb.alibabacloud.crossplane.io/v1alpha1
kind: LoadBalancerSecurityGroupAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/loadbalancersecuritygroupattachment
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    loadBalancerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: create_alb
    region: cn-beijing
    securityGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: create_security_group

---

apiVersion: alb.alibabacloud.crossplane.io/v1alpha1
kind: LoadBalancer
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/loadbalancersecuritygroupattachment
  labels:
    testing.upbound.io/example-name: create_alb
  name: create-alb
spec:
  forProvider:
    addressAllocatedMode: Fixed
    addressType: Intranet
    loadBalancerBillingConfig:
    - payType: PayAsYouGo
    loadBalancerEdition: Standard
    loadBalancerName: ${var.name}
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: create_vpc
    zoneMappings:
    - vswitchIdSelector:
        matchLabels:
          testing.upbound.io/example-name: create_vsw_2
      zoneIdSelector:
        matchLabels:
          testing.upbound.io/example-name: alicloud_zones
    - vswitchIdSelector:
        matchLabels:
          testing.upbound.io/example-name: create_vsw_1
      zoneIdSelector:
        matchLabels:
          testing.upbound.io/example-name: alicloud_zones

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/loadbalancersecuritygroupattachment
  labels:
    testing.upbound.io/example-name: create_security_group
  name: create-security-group
spec:
  forProvider:
    name: ${var.name}
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: create_vpc

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/loadbalancersecuritygroupattachment
  labels:
    testing.upbound.io/example-name: create_vpc
  name: create-vpc
spec:
  forProvider:
    cidrBlock: 192.168.0.0/16
    region: cn-beijing
    vpcName: ${var.name}

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/loadbalancersecuritygroupattachment
  labels:
    testing.upbound.io/example-name: create_vsw_1
  name: create-vsw-1
spec:
  forProvider:
    cidrBlock: 192.168.1.0/24
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: create_vpc
    vswitchName: ${var.name}
    zoneId: ${data.alicloud_zones.default.zones.0.id}

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/loadbalancersecuritygroupattachment
  labels:
    testing.upbound.io/example-name: create_vsw_2
  name: create-vsw-2
spec:
  forProvider:
    cidrBlock: 192.168.2.0/24
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: create_vpc
    vswitchName: ${var.name}
    zoneId: ${data.alicloud_zones.default.zones.1.id}
